name: Create Release based on a tag

on:
  push:
    tags:
      - "v*" # Only trigger on tags starting with v
  workflow_dispatch:

permissions:
  contents: write # To create releases and upload assets

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2.3.3
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
